
development:
  adapter: postgresql
  encoding: unicode
  database: blind_love_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: blind_love_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: blind_love_production
  pool: 5
  username: postgres
  password:
